name: senior_debug
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/FMotalleb/dart_senior_debug

environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  stack_trace: ^1.11.1
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
